application: e-benta
version: 2
runtime: python27
api_version: 1
threadsafe: yes
#default_expiration: "1h"

handlers:
- url: /book/list.txt
  static_files: list.txt
  upload: list.txt

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: /static/favicon\.ico

- url: /static
  static_dir: static  

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: latest