from google.appengine.api import mail
from pagehandlers.PageHandler import *

sender = "eBenta.com.ph <admin@ebenta.com.ph>"
class EmailHandler():
    @classmethod
    def welcomeUser(cls,user):
        subject = "Welcome to eBenta!"
        body = """
Hi %(full_name)s!

Welcome to eBenta.com.ph! Our goal here at eBenta is to provide you (and other scholars) a platform where you could purchase and consign(sell) books. We are also planning to expand our services to other academic materials such as readings. As of now we offer the following services:

Purchasing of used or second hand quality books:
    Purchase books previously used and owned by scholars like yourself, at LOWER prices! Save up to 50%% on you book allowance!!
    Items will be checked by us to ensure quality and your satisfaction.

Purchasing of Brand New Books:
    If you prefer to purchase new books than used ones, well why not? Just request for a brand new copy on the books information page.

Consigning of used books:
    If you are not familiar with the word, consigning is very much like selling, but better. The formal definition of consigning is placing any material in the hand of another, but retaining ownership until the goods are sold or person is transferred. In other words, eBenta.com.ph sells your books for you! Hassle free isn't it?

    How consignment works:
        1. Search for the book you would like to consign, or
        2. Fill-up the request to consign form in ebenta.com.ph/consign.
        3. Wait for an administrator to contact you regarding your request.
        4. Agree on a price you would like your book to be sold.
        5. Wait for your book to be sold.
        6. Once your book has been sold, you will be notified thru email and/or SMS.
        7. Get your profit from eBenta.com.ph. Yay!!
    Note: You may withdraw your consigned item from us anytime.

This is an autogenerated message. You may reply to this email address to contact our administrators.
""" %{"full_name":user.completeName().strip()}
        mail.send_mail(sender,user.email,subject,body)

    @classmethod
    def forgotPassword(cls,user,reset_link):
        subject = "Password Recovery"
        body="""
Hi %(full_name)s!

A request to reset your password has been sent to our system at %(time_sent)s.

If you have requested for this action, please click this link http://ebenta.com.ph/login/reset/%(reset_link)s to reset your eBenta.com.ph password.

If you havent authorized this action, just ignore this message. This reset link will expire in a few hours.

This is an autogenerated message. You may reply to this email address to contact our administrators.
""" %{"full_name":user.completeName.strip(),"time_sent":cls.getTimeNow(),"reset_link":reset_link}
    mail.send_mail(sender,user.email,subject,body)
    
    def getTimeNow(cls):
        return datetime.datetime.now().strftime("%B %d %H:%M:%S")